# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/myfunc_0/myfunc_0.xci
# IP: The module: 'myfunc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/myfunc_0/constraints/myfunc_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'myfunc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/myfunc_0/myfunc_0.xci
# IP: The module: 'myfunc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/myfunc_0/constraints/myfunc_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'myfunc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
