# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xcku15p-ffva1760-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.cache/wt [current_project]
set_property parent.project_path /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/user_ip_repo [current_project]
update_ip_catalog
set_property ip_output_repo /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/links/be_mgt/common/firmware/gen_hdl/aurora_64b66b_descrambler.v
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/links/be_mgt/common/firmware/gen_hdl/aurora_64b66b_scrambler.v
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/links/be_mgt/common/firmware/gen_hdl/gtwizard_ultrascale_0_prbs_any.v
}
read_vhdl -library xil_defaultlib {
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/w4-algo-repo/w4-algo/firmware/hdl/dc_ku15p_decl.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/boards/serenity/dc_ku15p/firmware/hdl/emp_device_decl_sm1_v2.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/links/be_mgt/common/firmware/hdl/links_cs_interface.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/links/be_mgt/common/firmware/hdl/package_links.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/links/be_mgt/common/firmware/hdl/ucrc_pkg.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/links/be_mgt/common/firmware/hdl/ucrc_par.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/links/be_mgt/common/firmware/hdl/ultrascale_fifo_stimulus_64b66b.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/links/be_mgt/common/firmware/hdl/bit_synchronizer.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/links/be_mgt/common/firmware/hdl/aurora_descrambler.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/links/be_mgt/common/firmware/hdl/aurora_scrambler.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/links/be_mgt/common/firmware/hdl/tx_fifo_top.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/links/be_mgt/common/firmware/hdl/tx_fifo_pkg.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/links/be_mgt/common/firmware/hdl/tx_fifo_cdc.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/links/be_mgt/common/firmware/hdl/rx_fifo_cdc.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/links/be_mgt/common/firmware/hdl/reset_synchronizer.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/links/be_mgt/common/firmware/hdl/link_status.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/links/be_mgt/common/firmware/hdl/links_crc_tx.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/links/be_mgt/common/firmware/hdl/links_crc_rx.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/links/be_mgt/common/firmware/hdl/initialization_fsm.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/links/be_mgt/common/firmware/hdl/data_quality_with_idle.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/links/be_mgt/common/firmware/hdl/add_padding_and_prbs_data.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/links/be_mgt/common/firmware/hdl/gtwizard_ultrascale_top.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/links/be_mgt/common/firmware/hdl/async_mgt_wrapper.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/ipbus-firmware/components/ipbus_core/firmware/hdl/ipbus_package.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/ipbus-firmware/components/ipbus_slaves/firmware/hdl/ipbus_reg_types.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/ipbus-firmware/components/ipbus_slaves/firmware/hdl/ipbus_ctrlreg_v.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/ipbus-firmware/components/ipbus_slaves/firmware/hdl/ipbus_reg_v.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/ipbus-firmware/components/ipbus_slaves/firmware/hdl/drp_decl.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/ipbus-firmware/components/ipbus_slaves/firmware/hdl/ipbus_drp_bridge.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/ipbus-firmware/components/ipbus_slaves/firmware/hdl/syncreg_r.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/ipbus-firmware/components/ipbus_slaves/firmware/hdl/syncreg_w.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/ipbus-firmware/components/ipbus_slaves/firmware/hdl/ipbus_syncreg_v.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/links/be_mgt/interface/firmware/hdl/emp_be_mgt.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/boards/serenity/common/firmware/hdl/emp_slim_top_decl.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/framework/firmware/hdl/emp_framework_decl.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/framework/firmware/hdl/emp_device_types.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/utils/firmware/hdl/ipbus_decode_top_emp_slim.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/ipbus-firmware/components/ipbus_core/firmware/hdl/ipbus_dc_node.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/ipbus-firmware/components/ipbus_core/firmware/hdl/ipbus_dc_fabric_sel.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/ipbus-firmware/components/ipbus_core/firmware/hdl/ipbus_fabric_sel.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/ipbus-firmware/components/ipbus_slaves/firmware/hdl/freq_ctr_div.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/ipbus-firmware/components/ipbus_slaves/firmware/hdl/ipbus_ported_dpram72.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/datapath/firmware/hdl/emp_data_types.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/ttc/firmware/hdl/emp_ttc_decl.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/datapath/firmware/hdl/usp/emp_ibufds_gt.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/datapath/firmware/hdl/ipbus_decode_emp_chan_buffer.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/datapath/firmware/hdl/drp_mux.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/ipbus-firmware/components/ipbus_util/firmware/hdl/del_array.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/datapath/firmware/hdl/emp_chan_buffer.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/ttc/firmware/hdl/bunch_ctr.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/datapath/firmware/hdl/align_mon.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/datapath/firmware/hdl/ipbus_decode_emp_region.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/datapath/firmware/hdl/emp_datapath_utils.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/datapath/firmware/hdl/emp_region.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/datapath/firmware/hdl/region_info.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/datapath/firmware/hdl/ipbus_decode_emp_datapath.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/datapath/firmware/hdl/emp_datapath.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/ipbus-firmware/components/ipbus_slaves/firmware/hdl/ipbus_freq_ctr.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/ttc/firmware/hdl/tmt_sync.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/ipbus-firmware/components/ipbus_slaves/firmware/hdl/ipbus_ported_sdpram72.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/ttc/firmware/hdl/ipbus_decode_emp_state_history.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/ttc/firmware/hdl/state_history.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/ttc/firmware/hdl/ttc_history_new.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/ttc/firmware/hdl/ttc_cmd_ctrs.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/ttc/firmware/hdl/ttc_ctrs.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/ttc/firmware/hdl/rng_n1024_r32_t5_k32_s1c48.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/ttc/firmware/hdl/rng_wrapper.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/ttc/firmware/hdl/l1a_gen.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/ttc/firmware/hdl/ipbus_decode_emp_ttc.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/ttc/firmware/hdl/emp_ttc_cmd.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/legacy_ttc/sources/synth/ttc_codec/hdl/ttc_codec_pkg.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/legacy_ttc/sources/synth/ttc_codec/hdl/dec/serialb_com.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/legacy_ttc/sources/synth/ttc_codec/hdl/dec/cdr2a_b_clk.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/legacy_ttc/sources/synth/ttc_codec/hdl/dec/ttc_decoder_core.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/legacy_ttc/sources/synth/ttc_codec/hdl/dec/ttc_decoder.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/ttc/firmware/hdl/usp/emp_ttc_clocks.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/ttc/firmware/hdl/emp_ttc.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/ctrl/firmware/hdl/ipbus_decode_emp_ctrl.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/ctrl/firmware/hdl/usp/board_const_reg_legacy.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/ctrl/firmware/hdl/emp_ctrl.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/info/firmware/hdl/emp_info.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/ipbus-firmware/components/ipbus_core/firmware/hdl/ipbus_trans_decl.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/ipbus-firmware/components/ipbus_core/firmware/hdl/transactor_cfg.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/ipbus-firmware/components/ipbus_core/firmware/hdl/transactor_sm.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/ipbus-firmware/components/ipbus_core/firmware/hdl/transactor_if.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/ipbus-firmware/components/ipbus_core/firmware/hdl/transactor.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/ipbus-firmware/components/ipbus_transport_axi/firmware/hdl/ipbus_axi_decl.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/ipbus-firmware/components/ipbus_transport_axi/firmware/hdl/ipbus_transport_multibuffer_tx_dpram.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/ipbus-firmware/components/ipbus_transport_axi/firmware/hdl/ipbus_transport_multibuffer_rx_dpram.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/ipbus-firmware/components/ipbus_transport_axi/firmware/hdl/ipbus_transport_multibuffer_cdc.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/ipbus-firmware/components/ipbus_transport_axi/firmware/hdl/ipbus_transport_multibuffer_if.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/ipbus-firmware/components/ipbus_transport_axi/firmware/hdl/ipbus_transport_ram_if.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/ipbus-firmware/components/ipbus_transport_axi/firmware/hdl/ipbus_transport_axi_if.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/ipbus-firmware/components/ipbus_pcie/firmware/hdl/pcie_int_gen_msix.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/ipbus-firmware/components/ipbus_pcie/firmware/hdl/pcie_xdma_axi_usp_if.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/ipbus-firmware/components/ipbus_util/firmware/hdl/ipbus_clock_div.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/ipbus-firmware/components/ipbus_util/firmware/hdl/clocks/clocks_usp_serdes.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/utils/firmware/hdl/usp/emp_oscclk.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/utils/firmware/hdl/usp/emp_slim_infra.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/emp-fwk/components/utils/firmware/hdl/emp_top.vhd
  /storage1/ag17009/IPBB_TestBuilds/w4_emp/src/w4-algo-repo/w4-algo/firmware/hdl/emp_payload.vhd
}
read_ip -quiet /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/myfunc_0/myfunc_0.xci
set_property used_in_implementation false [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/myfunc_0/constraints/myfunc_ooc.xdc]

read_ip -quiet /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/bram_rx_buffer/bram_rx_buffer.xci
set_property used_in_implementation false [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/bram_rx_buffer/bram_rx_buffer_ooc.xdc]

read_ip -quiet /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/tx_fifo/tx_fifo.xci
set_property used_in_synthesis 0 [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/tx_fifo/tx_fifo.xdc]
set_property used_in_implementation 0 [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/tx_fifo/tx_fifo.xdc]
set_property used_in_synthesis 0 [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/tx_fifo/tx_fifo_clocks.xdc]
set_property used_in_implementation 0 [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/tx_fifo/tx_fifo_clocks.xdc]
set_property used_in_synthesis 0 [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/tx_fifo/tx_fifo_ooc.xdc]
set_property used_in_implementation 0 [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/tx_fifo/tx_fifo_ooc.xdc]
set_property used_in_synthesis false [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/tx_fifo/tx_fifo.xdc]
set_property used_in_implementation false [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/tx_fifo/tx_fifo.xdc]
set_property used_in_synthesis false [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/tx_fifo/tx_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/tx_fifo/tx_fifo_clocks.xdc]
set_property used_in_synthesis false [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/tx_fifo/tx_fifo_ooc.xdc]
set_property used_in_implementation false [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/tx_fifo/tx_fifo_ooc.xdc]

read_ip -quiet /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/gtwizard_ultrascale_gty25g/gtwizard_ultrascale_gty25g.xci
set_property used_in_synthesis 0 [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/gtwizard_ultrascale_gty25g/synth/gtwizard_ultrascale_gty25g_ooc.xdc]
set_property used_in_implementation 0 [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/gtwizard_ultrascale_gty25g/synth/gtwizard_ultrascale_gty25g_ooc.xdc]
set_property used_in_synthesis 0 [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/gtwizard_ultrascale_gty25g/synth/gtwizard_ultrascale_gty25g.xdc]
set_property used_in_implementation 0 [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/gtwizard_ultrascale_gty25g/synth/gtwizard_ultrascale_gty25g.xdc]
set_property used_in_synthesis false [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/gtwizard_ultrascale_gty25g/synth/gtwizard_ultrascale_gty25g_ooc.xdc]
set_property used_in_implementation false [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/gtwizard_ultrascale_gty25g/synth/gtwizard_ultrascale_gty25g_ooc.xdc]
set_property used_in_synthesis false [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/gtwizard_ultrascale_gty25g/synth/gtwizard_ultrascale_gty25g.xdc]
set_property used_in_implementation false [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/gtwizard_ultrascale_gty25g/synth/gtwizard_ultrascale_gty25g.xdc]

read_ip -quiet /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/gtwizard_ultrascale_gty16g/gtwizard_ultrascale_gty16g.xci
set_property used_in_synthesis 0 [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/gtwizard_ultrascale_gty16g/synth/gtwizard_ultrascale_gty16g_ooc.xdc]
set_property used_in_implementation 0 [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/gtwizard_ultrascale_gty16g/synth/gtwizard_ultrascale_gty16g_ooc.xdc]
set_property used_in_synthesis 0 [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/gtwizard_ultrascale_gty16g/synth/gtwizard_ultrascale_gty16g.xdc]
set_property used_in_implementation 0 [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/gtwizard_ultrascale_gty16g/synth/gtwizard_ultrascale_gty16g.xdc]
set_property used_in_synthesis false [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/gtwizard_ultrascale_gty16g/synth/gtwizard_ultrascale_gty16g_ooc.xdc]
set_property used_in_implementation false [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/gtwizard_ultrascale_gty16g/synth/gtwizard_ultrascale_gty16g_ooc.xdc]
set_property used_in_synthesis false [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/gtwizard_ultrascale_gty16g/synth/gtwizard_ultrascale_gty16g.xdc]
set_property used_in_implementation false [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/gtwizard_ultrascale_gty16g/synth/gtwizard_ultrascale_gty16g.xdc]

read_ip -quiet /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/gtwizard_ultrascale_gth16g/gtwizard_ultrascale_gth16g.xci
set_property used_in_synthesis 0 [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/gtwizard_ultrascale_gth16g/synth/gtwizard_ultrascale_gth16g_ooc.xdc]
set_property used_in_implementation 0 [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/gtwizard_ultrascale_gth16g/synth/gtwizard_ultrascale_gth16g_ooc.xdc]
set_property used_in_synthesis 0 [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/gtwizard_ultrascale_gth16g/synth/gtwizard_ultrascale_gth16g.xdc]
set_property used_in_implementation 0 [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/gtwizard_ultrascale_gth16g/synth/gtwizard_ultrascale_gth16g.xdc]
set_property used_in_synthesis false [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/gtwizard_ultrascale_gth16g/synth/gtwizard_ultrascale_gth16g_ooc.xdc]
set_property used_in_implementation false [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/gtwizard_ultrascale_gth16g/synth/gtwizard_ultrascale_gth16g_ooc.xdc]
set_property used_in_synthesis false [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/gtwizard_ultrascale_gth16g/synth/gtwizard_ultrascale_gth16g.xdc]
set_property used_in_implementation false [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/gtwizard_ultrascale_gth16g/synth/gtwizard_ultrascale_gth16g.xdc]

read_ip -quiet /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/axi_bram_ctrl_0/axi_bram_ctrl_0.xci
set_property used_in_implementation false [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/axi_bram_ctrl_0/axi_bram_ctrl_0_ooc.xdc]

read_ip -quiet /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/xdma_0/xdma_0.xci
set_property used_in_implementation false [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/xdma_0/ip_2/xdma_v4_1_4_blk_mem_64_noreg_be_ooc.xdc]
set_property used_in_implementation false [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/xdma_0/ip_1/xdma_v4_1_4_blk_mem_64_reg_be_ooc.xdc]
set_property used_in_implementation false [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/xdma_0/ip_0/ip_0/synth/xdma_0_pcie4_ip_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/xdma_0/ip_0/ip_0/synth/xdma_0_pcie4_ip_gt.xdc]
set_property used_in_implementation false [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/xdma_0/ip_0/xdma_0_pcie4_ip_board.xdc]
set_property used_in_implementation false [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/xdma_0/ip_0/synth/xdma_0_pcie4_ip_ooc.xdc]
set_property used_in_implementation false [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/xdma_0/ip_0/synth/xdma_0_pcie4_ip_late.xdc]
set_property used_in_implementation false [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/xdma_0/ip_0/source/ip_pcie4_uscale_plus_x1y0.xdc]
set_property used_in_implementation false [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/xdma_0/xdma_0_board.xdc]
set_property used_in_implementation false [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/xdma_0/source/xdma_0_pcie4_uscaleplus_ip.xdc]
set_property used_in_implementation false [get_files -all /storage1/ag17009/IPBB_TestBuilds/w4_emp/proj/w4_algo/w4_algo/w4_algo.srcs/sources_1/ip/xdma_0/synth/xdma_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xcku15p-ffva1760-2-e -flatten_hierarchy none -assert


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
